// 17 Nov 2022

#define MAXROUNDS 12
#define NROWS 3
#define NCOLUMS 4
#define NLANES (NCOLUMS*NROWS)

#define LANESIZE 4
#define LANES_PER_PLANE 3
#define PLANE_SIZE LANES_PER_PLANE * 4
#define NPLANES 3
